# Custom Settings
# monitor = eDP-1, auto, auto, 1
 
input {
    sensitivity = -1.0 # -1.0 - 1.0, 0 means no modification.
    repeat_delay = 250
    repeat_rate = 50
}

env = QT_QPA_PLATFORMTHEME,qt5ct
