################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# Go to "custom/general" to configure your monitor, don't touch this
monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm
$fileManager = nautilus
$browser = zen-browser
$monitor = gnome-system-monitor
$menu = wofi --show drun

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = swww-daemon
exec-once = wal -R -n
exec-once = swaync
exec-once = hyprpm reload -n
exec-once = hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = pywalfox start
exec-once = waybar

#############
## SOURCES ## 
#############
source = ~/.config/hypr/config/*.conf
source = ~/.config/hypr/custom/*.conf

#############################
## ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct

layerrule = blur, wofi
layerrule = ignorezero, wofi
layerrule = ignorealpha 0.5, wofi
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

